//
//  CircadianWidgetBundle.swift
//  CircadianWidget
//
//  Created by Maximilian Mäser on 7/9/25.
//

import WidgetKit
import SwiftUI

// This file is automatically generated and should remain minimal
// The main widget bundle is defined in CircadianWidget.swift